### ISSUE TITLE
Adding More Curl Option Support.

### ISSUE THREAD

**Issue by vijayrsv** [vijayrsv/ruby-curl#7]
- [x] - CURLOPT_WRITEFUNCTION
- [x] - CURLOPT_HEADERFUNCTION
- [x] - CURLOPT_READFUNCTION
- [x] - CURLOPT_FOLLOWLOCATION
- [x] - CURLOPT_MAXREDIRS

**Comment by singhshivam** [comment]
# Vijay

- [x] CURLOPT_AUTOREFERER
- [x] CURLOPT_BUFFERSIZE
- [x] CURLOPT_CAINFO
- [x] CURLOPT_CAPATH
- [x] CURLOPT_CONNECTTIMEOUT
- [x] CURLOPT_COOKIE
- [x] CURLOPT_COOKIEFILE
- [x] CURLOPT_COOKIEJAR
- [x] CURLOPT_COOKIESESSION
- [x] CURLOPT_CRLF
- [x] CURLOPT_CUSTOMREQUEST
- [x] CURLOPT_DNS_CACHE_TIMEOUT
- [x] CURLOPT_DNS_USE_GLOBAL_CACHE
- [x] CURLOPT_EGDSOCKET
- [x] CURLOPT_ENCODING
- [x] CURLOPT_FAILONERROR
- [x] CURLOPT_FILETIME
- [x] CURLOPT_FOLLOWLOCATION
- [x] CURLOPT_FORBID_REUSE
- [x] CURLOPT_FRESH_CONNECT
~~CURLOPT_FTPPORT~~
~~CURLOPT_FTP_USE_EPRT~~
~~CURLOPT_FTP_USE_EPSV~~
- [x] CURLOPT_HEADER
- [x] CURLOPT_HEADERFUNCTION
- [x] CURLOPT_HTTP200ALIASES
- [x] CURLOPT_HTTPGET
- [x] CURLOPT_HTTPHEADER
- [x] CURLOPT_HTTPPROXYTUNNEL
- [x] CURLOPT_HTTP_VERSION
- [x] CURLOPT_INFILESIZE
- [x] CURLOPT_INTERFACE
- [x] CURLOPT_LOW_SPEED_LIMIT
- [x] CURLOPT_LOW_SPEED_TIME
- [x] CURLOPT_MAXCONNECTS
- [x] CURLOPT_MAXREDIRS
- [x] CURLOPT_NETRC
- [x] CURLOPT_NOBODY
- [x] CURLOPT_NOPROGRESS
- [x] CURLOPT_NOSIGNAL
- [x] CURLOPT_PORT
- [x] CURLOPT_POST
- [x] CURLOPT_POSTFIELDS
~~CURLOPT_POSTQUOTE~~
~~CURLOPT_PREQUOTE~~
~~CURLOPT_PRIVATE~~
~~CURLOPT_PROGRESSFUNCTION~~
- [x] CURLOPT_PROXY
- [x] CURLOPT_PROXYPORT
- [x] CURLOPT_PROXYTYPE
- [x] CURLOPT_PROXYUSERPWD
- [x] CURLOPT_PUT
~~CURLOPT_QUOTE~~
- [x] CURLOPT_RANDOM_FILE
- [x] CURLOPT_RANGE
- [x] CURLOPT_READDATA
- [x] CURLOPT_READFUNCTION
- [x] CURLOPT_REFERER
- [x] CURLOPT_RESUME_FROM
~~CURLOPT_SHARE~~
- [x] CURLOPT_SSLCERT
- [x] CURLOPT_SSLCERTTYPE
- [x] CURLOPT_SSLENGINE
- [x] CURLOPT_SSLENGINE_DEFAULT
- [x] CURLOPT_SSLKEY
- [x] CURLOPT_SSLKEYTYPE
- [x] CURLOPT_SSLVERSION
- [x] CURLOPT_SSL_CIPHER_LIST
- [x] CURLOPT_SSL_VERIFYHOST
- [x] CURLOPT_SSL_VERIFYPEER
~~CURLOPT_STDERR~~
~~CURLOPT_TELNETOPTIONS~~
- [x] CURLOPT_TIMECONDITION
- [x] CURLOPT_TIMEOUT
- [x] CURLOPT_TIMEVALUE
~~CURLOPT_TRANSFERTEXT~~
- [x] CURLOPT_UNRESTRICTED_AUTH

# Shivam
- [x] CURLOPT_UPLOAD
- [x] CURLOPT_URL
- [x] CURLOPT_USERAGENT
- [x] CURLOPT_USERPWD
- [x] CURLOPT_VERBOSE
- [x] CURLOPT_WRITEFUNCTION
- [ ] CURLOPT_WRITEHEADER
- [x] CURLOPT_HTTPAUTH
~~CURLOPT_FTP_CREATE_MISSING_DIRS~~
- [x] CURLOPT_PROXYAUTH
~~CURLOPT_FTP_RESPONSE_TIMEOUT~~
- [x] CURLOPT_IPRESOLVE
- [x] CURLOPT_MAXFILESIZE
- [x] CURLOPT_NETRC_FILE
~~CURLOPT_FTPSSLAUTH~~
~~CURLOPT_FTP_ACCOUNT~~
- [x] CURLOPT_TCP_NODELAY
- [x] CURLOPT_COOKIELIST
- [x] CURLOPT_IGNORE_CONTENT_LENGTH
~~CURLOPT_FTP_SKIP_PASV_IP~~
~~CURLOPT_FTP_FILEMETHOD~~
- [x] CURLOPT_CONNECT_ONLY
- [x] CURLOPT_LOCALPORT
~~CURLOPT_FTP_ALTERNATIVE_TO_USER~~
- [x] CURLOPT_MAX_RECV_SPEED_LARGE
- [x] CURLOPT_MAX_SEND_SPEED_LARGE
- [x] CURLOPT_SSL_SESSIONID_CACHE
~~CURLOPT_FTP_SSL_CCC~~
~~CURLOPT_SSH_AUTH_TYPES~~
~~CURLOPT_SSH_PRIVATE_KEYFILE~~
~~CURLOPT_SSH_PUBLIC_KEYFILE~~
- [x] CURLOPT_CONNECTTIMEOUT_MS
- [x] CURLOPT_HTTP_CONTENT_DECODING
- [x] CURLOPT_HTTP_TRANSFER_DECODING
- [x] CURLOPT_TIMEOUT_MS
- [x] CURLOPT_KRBLEVEL
~~CURLOPT_NEW_DIRECTORY_PERMS~~
~~CURLOPT_NEW_FILE_PERMS~~
~~CURLOPT_APPEND~~
~~CURLOPT_DIRLISTONLY~~
~~CURLOPT_USE_SSL~~
~~CURLOPT_SSH_HOST_PUBLIC_KEY_MD5~~
~~CURLOPT_PROXY_TRANSFER_MODE~~
- [x] CURLOPT_ADDRESS_SCOPE
- [x] CURLOPT_CRLFILE
- [x] CURLOPT_ISSUERCERT
- [x] CURLOPT_KEYPASSWD
- [x] CURLOPT_CERTINFO
- [x] CURLOPT_PASSWORD
- [x] CURLOPT_POSTREDIR
- [x] CURLOPT_USERNAME
- [x] CURLOPT_NOPROXY
- [x] CURLOPT_PROTOCOLS
- [x] CURLOPT_REDIR_PROTOCOLS
- [x] CURLOPT_SOCKS5_GSSAPI_NEC
- [x] CURLOPT_SOCKS5_GSSAPI_SERVICE
~~CURLOPT_TFTP_BLKSIZE~~
~~CURLOPT_SSH_KNOWNHOSTS~~
~~CURLOPT_FTP_USE_PRET~~
~~CURLOPT_MAIL_FROM~~
~~CURLOPT_MAIL_RCPT~~
~~CURLOPT_RTSP_CLIENT_CSEQ~~
~~CURLOPT_RTSP_REQUEST~~
~~CURLOPT_RTSP_SERVER_CSEQ~~
~~CURLOPT_RTSP_SESSION_ID~~
~~CURLOPT_RTSP_STREAM_URI~~
~~CURLOPT_RTSP_TRANSPORT~~
~~CURLOPT_FNMATCH_FUNCTION~~
- [x] CURLOPT_RESOLVE
- [x] CURLOPT_TLSAUTH_PASSWORD
- [x] CURLOPT_TLSAUTH_TYPE
- [x] CURLOPT_TLSAUTH_USERNAME
- [x] CURLOPT_GSSAPI_DELEGATION
- [x] CURLOPT_PROXYHEADER
- [x] CURLOPT_UNIX_SOCKET_PATH
- [x] CURLOPT_PATH_AS_IS
- [x] CURLOPT_PIPEWAIT
